version: '3.9'
services:
  i_give_up:
    container_name: i_give_up
    # command: yarn docker-develop
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - i_give_up_postgres
    volumes:
      - .:/app
      - ./src/public:/app/dist/public
      - ./src:/app/src
      - ./dist:/app/dist

  i_give_up_pgadmin:
    container_name: i_give_up_pgadmin
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    depends_on:
      - i_give_up_postgres

  i_give_up_postgres:
    container_name: i_give_up_postgres
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - i_give_up:/data/db_i_give_up_postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
 i_give_up: {}
