version: '3.9'
services:
  retailer-product-service:
    container_name: retailer-product-service
    # command: yarn docker-develop
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./src/public:/app/dist/public
      - ./src:/app/src
      - ./dist:/app/dist

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
 postgres: {}
